# enum_discrim_align_threshold = 15
# error_on_line_overflow = true
max_width = 80
# imports_granularity = "Module"
# merge_imports = true

newline_style = "Unix"

# group_imports = "StdExternalCrate"

use_field_init_shorthand = true
